package TestUI;

public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form AFrame
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        topBar = new javax.swing.JPanel();
        unitsBox = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        turretsBox = new javax.swing.JPanel();
        specialsBox = new javax.swing.JPanel();
        upgradesBox = new javax.swing.JPanel();
        mainGame = new javax.swing.JPanel();
        lowerBar = new javax.swing.JPanel();
        timeControlBar = new javax.swing.JPanel();
        hpPanel = new javax.swing.JPanel();
        hpBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(100, 242, 242));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        topBar.setBackground(new java.awt.Color(242, 242, 42));
        topBar.setPreferredSize(new java.awt.Dimension(0, 75));
        topBar.setLayout(new javax.swing.BoxLayout(topBar, javax.swing.BoxLayout.LINE_AXIS));

        unitsBox.setBackground(new java.awt.Color(124, 50, 42));
        unitsBox.setLayout(new java.awt.GridLayout(1, 0, 20, 10));

        jPanel1.setPreferredSize(new java.awt.Dimension(44, 44));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        unitsBox.add(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        unitsBox.add(jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        unitsBox.add(jPanel3);

        topBar.add(unitsBox);

        turretsBox.setBackground(new java.awt.Color(22, 100, 242));

        javax.swing.GroupLayout turretsBoxLayout = new javax.swing.GroupLayout(turretsBox);
        turretsBox.setLayout(turretsBoxLayout);
        turretsBoxLayout.setHorizontalGroup(
                turretsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 169, Short.MAX_VALUE));
        turretsBoxLayout.setVerticalGroup(
                turretsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 55, Short.MAX_VALUE));

        topBar.add(turretsBox);

        specialsBox.setBackground(new java.awt.Color(124, 50, 142));
        specialsBox.setPreferredSize(new java.awt.Dimension(76, 57));

        javax.swing.GroupLayout specialsBoxLayout = new javax.swing.GroupLayout(specialsBox);
        specialsBox.setLayout(specialsBoxLayout);
        specialsBoxLayout.setHorizontalGroup(
                specialsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 76, Short.MAX_VALUE));
        specialsBoxLayout.setVerticalGroup(
                specialsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 55, Short.MAX_VALUE));

        topBar.add(specialsBox);

        upgradesBox.setBackground(new java.awt.Color(2, 150, 22));

        javax.swing.GroupLayout upgradesBoxLayout = new javax.swing.GroupLayout(upgradesBox);
        upgradesBox.setLayout(upgradesBoxLayout);
        upgradesBoxLayout.setHorizontalGroup(
                upgradesBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 208, Short.MAX_VALUE));
        upgradesBoxLayout.setVerticalGroup(
                upgradesBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 55, Short.MAX_VALUE));

        topBar.add(upgradesBox);

        getContentPane().add(topBar);

        mainGame.setBackground(new java.awt.Color(242, 42, 242));
        mainGame.setForeground(new java.awt.Color(100, 0, 0));
        mainGame.setPreferredSize(new java.awt.Dimension(625, 400));

        javax.swing.GroupLayout mainGameLayout = new javax.swing.GroupLayout(mainGame);
        mainGame.setLayout(mainGameLayout);
        mainGameLayout.setHorizontalGroup(
                mainGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 625, Short.MAX_VALUE));
        mainGameLayout.setVerticalGroup(
                mainGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 297, Short.MAX_VALUE));

        getContentPane().add(mainGame);

        lowerBar.setBackground(new java.awt.Color(22, 242, 242));
        lowerBar.setPreferredSize(new java.awt.Dimension(0, 50));

        timeControlBar.setBackground(new java.awt.Color(142, 92, 92));

        javax.swing.GroupLayout timeControlBarLayout = new javax.swing.GroupLayout(timeControlBar);
        timeControlBar.setLayout(timeControlBarLayout);
        timeControlBarLayout.setHorizontalGroup(
                timeControlBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 275, Short.MAX_VALUE));
        timeControlBarLayout.setVerticalGroup(
                timeControlBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        hpPanel.setBackground(new java.awt.Color(42, 242, 42));

        hpBar.setBackground(new java.awt.Color(255, 109, 109));

        javax.swing.GroupLayout hpPanelLayout = new javax.swing.GroupLayout(hpPanel);
        hpPanel.setLayout(hpPanelLayout);
        hpPanelLayout.setHorizontalGroup(
                hpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hpPanelLayout.createSequentialGroup()
                                .addContainerGap(57, Short.MAX_VALUE)
                                .addComponent(hpBar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)));
        hpPanelLayout.setVerticalGroup(
                hpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(hpPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(hpBar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addContainerGap()));

        javax.swing.GroupLayout lowerBarLayout = new javax.swing.GroupLayout(lowerBar);
        lowerBar.setLayout(lowerBarLayout);
        lowerBarLayout.setHorizontalGroup(
                lowerBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(lowerBarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(timeControlBar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120,
                                        Short.MAX_VALUE)
                                .addComponent(hpPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        lowerBarLayout.setVerticalGroup(
                lowerBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(lowerBarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(lowerBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(timeControlBar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(lowerBarLayout.createSequentialGroup()
                                                .addComponent(hpPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));

        getContentPane().add(lowerBar);

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    // /* Set the Nimbus look and feel */
    // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    // /* If Nimbus (introduced in Java SE 6) is not available, stay with the
    // default look and feel.
    // * For details see
    // http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
    // */
    // try {
    // for (javax.swing.UIManager.LookAndFeelInfo info :
    // javax.swing.UIManager.getInstalledLookAndFeels()) {
    // if ("Nimbus".equals(info.getName())) {
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    // }
    // } catch (ClassNotFoundException ex) {
    // java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (InstantiationException ex) {
    // java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (IllegalAccessException ex) {
    // java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    // java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // }
    // //</editor-fold>

    // System.out.println("AAAAaa");
    // /* Create and display the form */
    // new MainUI().setVisible(true);
    // // java.awt.EventQueue.invokeLater(new Runnable() {
    // // public void run() {
    // // new MainUI().setVisible(true);
    // // System.out.println("abc");
    // // }
    // // });
    // }

    // Variables declaration - do not modify
    private javax.swing.JProgressBar hpBar;
    private javax.swing.JPanel hpPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel lowerBar;
    private javax.swing.JPanel mainGame;
    private javax.swing.JPanel specialsBox;
    private javax.swing.JPanel timeControlBar;
    private javax.swing.JPanel topBar;
    private javax.swing.JPanel turretsBox;
    private javax.swing.JPanel unitsBox;
    private javax.swing.JPanel upgradesBox;
    // End of variables declaration
}
